version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: discord-bot-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=discord-bot
    restart: unless-stopped

volumes:
  mongodb_data:
